/// Flutter icons CustomIcons2
/// Copyright (C) 2025 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  CustomIcon2
///      fonts:
///       - asset: fonts/CustomIcon2.ttf
///
///
/// * Font Awesome 5, Copyright (C) 2016 by Dave Gandy
///         Author:    Dave Gandy
///         License:   SIL (https://github.com/FortAwesome/Font-Awesome/blob/master/LICENSE.txt)
///         Homepage:  http://fortawesome.github.com/Font-Awesome/
/// * Typicons, (c) Stephen Hutchings 2012
///         Author:    Stephen Hutchings
///         License:   SIL (http://scripts.sil.org/OFL)
///         Homepage:  http://typicons.com/
/// * Font Awesome 4, Copyright (C) 2016 by Dave Gandy
///         Author:    Dave Gandy
///         License:   SIL ()
///         Homepage:  http://fortawesome.github.com/Font-Awesome/
/// * Material Design Icons, Copyright (C) Google, Inc
///         Author:    Google
///         License:   Apache 2.0 (https://www.apache.org/licenses/LICENSE-2.0)
///         Homepage:  https://design.google.com/icons/
/// * Linecons, Copyright (C) 2013 by Designmodo
///         Author:    Designmodo for Smashing Magazine
///         License:   CC BY ()
///         Homepage:  http://designmodo.com/linecons-free/
/// * Zocial, Copyright (C) 2012 by Sam Collins
///         Author:    Sam Collins
///         License:   MIT (http://opensource.org/licenses/mit-license.php)
///         Homepage:  http://zocial.smcllns.com/
/// * MFG Labs, Copyright (C) 2012 by Daniel Bruce
///         Author:    MFG Labs
///         License:   SIL (http://scripts.sil.org/OFL)
///         Homepage:  http://www.mfglabs.com/
/// * Brandico, (C) 2012 by Vitaly Puzrin
///         Author:    Crowdsourced, for Fontello project
///         License:   SIL (http://scripts.sil.org/OFL)
///         Homepage:
/// * Entypo, Copyright (C) 2012 by Daniel Bruce
///         Author:    Daniel Bruce
///         License:   SIL (http://scripts.sil.org/OFL)
///         Homepage:  http://www.entypo.com
///
// ignore_for_file: dangling_library_doc_comments

import 'package:flutter/widgets.dart';

class CustomIcons2 {
  CustomIcons2._();

  static const _kFontFam = 'CustomIcon2';
  static const String? _kFontPkg = null;

  static const IconData youtube_1 =
      IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData instagramSquare =
      IconData(0xe801, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData linkedIn =
      IconData(0xe802, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData link =
      IconData(0xe803, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData insertLink =
      IconData(0xe804, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData globe =
      IconData(0xe805, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData globe_1 =
      IconData(0xe806, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData payment =
      IconData(0xe807, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData paypal2 =
      IconData(0xe808, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData amazon_1 =
      IconData(0xe809, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData linkedInCircled =
      IconData(0xf05b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData linkedIn1 =
      IconData(0xf05c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData linkExt =
      IconData(0xf08e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData faceBook =
      IconData(0xf09a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData link_1 =
      IconData(0xf0c1, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData gPlus =
      IconData(0xf0d5, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData unlink =
      IconData(0xf127, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData youtubeSquared =
      IconData(0xf166, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData youtube =
      IconData(0xf167, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData youtubePlay =
      IconData(0xf16a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData instagram =
      IconData(0xf16d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData apple =
      IconData(0xf179, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData gratipay =
      IconData(0xf184, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData google =
      IconData(0xf1a0, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData paypal =
      IconData(0xf1ed, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData ccPayPal =
      IconData(0xf1f4, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData whatsapp =
      IconData(0xf232, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData amazon =
      IconData(0xf270, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData faceBookSquared =
      IconData(0xf308, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData linkedInRect =
      IconData(0xf31b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData paypal_1 =
      IconData(0xf342, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData faceBookF =
      IconData(0xf39e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData faceBookMessenger =
      IconData(0xf39f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData googleDrive =
      IconData(0xf3aa, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData googlePlay =
      IconData(0xf3ab, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData applePay =
      IconData(0xf415, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData ccApplePay =
      IconData(0xf416, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData amazonPay =
      IconData(0xf42c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData ccAmazonPay =
      IconData(0xf42d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData globeAmericas =
      IconData(0xf57d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData hammer =
      IconData(0xf6e3, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
